version: "3.6"

services:

#Thermometer
    thermometer:
        container_name: "thermometer"
        build:
            context: ""
            dockerfile: src/main/java/Sensoren/Thermometer/Dockerfile
        image: verteilte_systeme/thermometer

    #Hygrometer
    hygrometer:
        container_name: "hygrometer"
        build:
            context: ""
            dockerfile: src/main/java/Sensoren/Hygrometer/Dockerfile
        image: verteilte_systeme/hygrometer

    #Light
    light:
        container_name: "light"
        build:
            context: ""
            dockerfile: src/main/java/Sensoren/Light/Dockerfile
        image: verteilte_systeme/light
    # Zentrale
    zentrale:
        container_name: "zentrale"
        build:
            context: ""
            dockerfile: src/main/java/Zentral/Dockerfile
        image: verteilte_systeme/zentrale

        ports:
            - "8080:8080"
            - "1234:1234"

   # Anbieter
   provider:
       container_name: "provider"
       build:
           context: ""
           dockerfile: src/main/java/ProviderServer/Dockerfile
       image: verteilte_systeme/provider
       ports:
           - "9090:9090"

#    mainclass:
#        container_name: "sensoren"
#        build:
#            context: ""
#            dockerfile: src/main/java/Sensoren/Dockerfile
#        image: verteilte_systeme/sensoren

