version: "3.6"
services:
#Thermometer
   thermometer:
       container_name: "Thermometer"
       build:
           context: ""
           dockerfile: src/main/java/Sensoren/Thermometer/Dockerfile
       image: verteilte_systeme/thermometer
       networks:
           verteilte_systeme:
               ipv4_address: "172.20.0.11"


       #Hygrometer
   hygrometer:
       container_name: "Hygrometer"
       build:
           context: ""
           dockerfile: src/main/java/Sensoren/Hygrometer/Dockerfile
       image: verteilte_systeme/hygrometer
       networks:
           verteilte_systeme:
               ipv4_address: "172.20.0.12"



       #Light
   light:
       container_name: "Light"
       build:
           context: ""
           dockerfile: src/main/java/Sensoren/Light/Dockerfile
       image: verteilte_systeme/light
       networks:
           verteilte_systeme:
               ipv4_address: "172.20.0.13"



        # Zentrale
   zentrale:
        container_name: "zentrale"
        build:
            context: ""
            dockerfile: src/main/java/Zentral/Dockerfile
        image: verteilte_systeme/zentrale
        ports:
            - "8080:8080"
            - "1234:1234"
        networks:
            verteilte_systeme:
                ipv4_address: "172.20.0.2"



        # Anbieter
   provider:
       container_name: "provider"
       build:
           context: ""
           dockerfile: src/main/java/ProviderServer/Dockerfile
       image: verteilte_systeme/provider
       ports:
           - "9090:9090"
       networks:
           verteilte_systeme:
               ipv4_address: "172.20.0.3"


    #Netzwerk
networks:
    verteilte_systeme:
        ipam:
            driver: default
            config:
                - subnet: "172.20.0.0/16"