version: "3.6"
services:
  #Thermometer
  thermometer:
    container_name: "Thermometer"
    build:
      context: ""
      dockerfile: src/main/java/Sensoren/Thermometer/Dockerfile
    image: verteilte_systeme/thermometer
    restart: always
    networks:
      verteilte_systeme:
        ipv4_address: 172.20.1.5


    #Hygrometer
  hygrometer:
    container_name: "Hygrometer"
    build:
      context: ""
      dockerfile: src/main/java/Sensoren/Hygrometer/Dockerfile
    image: verteilte_systeme/hygrometer
    restart: always
    networks:
      verteilte_systeme:
        ipv4_address: 172.20.1.6



    #Light
  light:
    container_name: "Light"
    build:
      context: ""
      dockerfile: src/main/java/Sensoren/Light/Dockerfile
    image: verteilte_systeme/light
    restart: always
    networks:
      verteilte_systeme:
        ipv4_address: 172.20.1.7


  #  sensorandcentral:
  #    container_name: "sns"
  #    build:
  #      context: ""
  #      dockerfile: src/main/java/Sensoren/Dockerfile
  #    image: verteilte_systeme/main
  #    restart: always
  #    ports:
  #      - "8080:8080"
  #      - "1234:1234"
  #    networks:
  #      verteilte_systeme:
  #        ipv4_address: "172.20.0.14"


  #MQTT
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always
    #    volumes:
    #      - ~/IdeaProjects/smart-home/mosquitto/config:/mosquitto/config
    #      - ~/IdeaProjects/smart-home/mosquitto/data:/mosquitto/data
    #      - ~/IdeaProjects/smart-home/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      verteilte_systeme:
        ipv4_address: 172.20.1.1


        # Zentrale
  zentrale:
    container_name: "zentrale"
    build:
      context: ""
      dockerfile: src/main/java/Zentral/Dockerfile
    image: verteilte_systeme/zentrale
    ports:
      - 8080:8080
      - 1234:1234
    networks:
      verteilte_systeme:
        ipv4_address: 172.20.1.8


    # Anbieter
  provider:
    container_name: "provider"
    build:
      context: ""
      dockerfile: src/main/java/ProviderServer/Dockerfile
    image: verteilte_systeme/provider
    restart: always
    ports:
      - 9090:9090
    networks:
      verteilte_systeme:
        ipv4_address: 172.20.1.9


  portainer:
    container_name: "portainer"
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

    ports:
      - 81:9000

    networks:
      verteilte_systeme:
        ipv4_address: 172.20.0.10


    #Volumes
volumes:
  portainer_data:
  #Netzwerk
networks:
  verteilte_systeme:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16